qfil:
  path: "../utils/QFIL/Qualcomm_Flash_Image_Loader_v2.0.3.5/QFIL.exe"
  window:
    position: [423, 125]
    size: [1000, 750]
    title_keywords: ["QFIL"]
  progress_pixel: [1402, 619]
  click_positions:
    select_port: [495, 280]
    firehose_btn: [1306, 356]
    rawprogram_btn: [1320, 550]
    patch_btn: [1315, 590]

files:
  default:  # 默认配置
    firehose: "C:/Users/CHP00015/Desktop/Image new one/RELEASE_IMAGES/2025-04-28_21_25/prog_firehose_ddr.elf"
    rawprogram: "C:/Users/CHP00015/Desktop/Image new one/RELEASE_IMAGES/2025-04-28_21_25/sail_nor/rawprogram0.xml"
    patch: "C:/Users/CHP00015/Desktop/Image new one/RELEASE_IMAGES/2025-04-28_21_25/sail_nor/patch0.xml"
  
  profile1:  # 其他配置文件集
    firehose: "path/to/other/prog_firehose_ddr.elf"
    rawprogram: "path/to/other/rawprogram0.xml"
    patch: "path/to/other/patch0.xml"